### ISSUE TITLE
Load the results is null,can't show the result

### ISSUE THREAD

**Issue by YaoCharlie** [thouska/spotpy#213]
When drawing the image after loading the result, the image cannot be seen and the display result is empty.

**Comment by thouska** [comment]
Hi @YaoCharlie,

thank yor for your message and sorry for the late response. I uploaded a fix for that, currently in a [branch](https://github.com/thouska/spotpy/tree/New-design-for-status-tracking/spotpy), which will be merged soon. If you want you can test it already. I will inform you, as soon as a new spotpy version is available.

**Comment by thouska** [comment]
FYI: I merged the [branch](https://github.com/thouska/spotpy/tree/New-design-for-status-tracking/spotpy) With the new available [>= version 1.5.0](https://pypi.org/project/spotpy/) the problem should be fixed. Feel free to re-open this issue in case of any problems.

**Comment by YaoCharlie** [comment]
Thank you for that,but the problems seems not to be solved.

thouska <notifications@github.com> 于2019年5月20日周一 下午5:04写道：

**Comment by thouska** [comment]
Thanks for testing this directly and reporting the remaining issue. Indeed there was a keyword missing, I uploaded a fix for that and changed also the documentation accordingly. You can find the new version ([>=1.5.1 on pypi](https://pypi.org/project/spotpy/)).

**Comment by YaoCharlie** [comment]
It still doesn't show the diagram, so you can see the error in the attached
diagram.

[image: 20190521230839.png]

thouska <notifications@github.com> 于2019年5月21日周二 下午4:32写道：
